/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_maropu_SQLSmithNative */

#ifndef _Included_io_github_maropu_SQLSmithNative
#define _Included_io_github_maropu_SQLSmithNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_maropu_SQLSmithNative
 * Method:    schemaInit
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_io_github_maropu_SQLSmithNative_schemaInit
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     io_github_maropu_SQLSmithNative
 * Method:    getSQLFuzz
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_maropu_SQLSmithNative_getSQLFuzz
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_github_maropu_SQLSmithNative
 * Method:    free
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_io_github_maropu_SQLSmithNative_free
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
